### ISSUE TITLE
GPL Licence

### ISSUE THREAD

**Issue by drasko** [cTn-dev/PyComms#1]
Hi Stefan,
I am writing you in front of WeIO project (https://github.com/nodesign/weio).

We have spotted your code and it seems as an interesting approach indeed. Great work!

We are considering integrating/linking parts of your code into our project. At this point we would like to ask you if you would like to stick to GPL licence, or do you consider changing this licence to something more permissive - MIT or BSD - as this approach is more gentle to the embedded industry.

On our side we are strongly considering this change (WeIO is GPL licenced also), but we would like to know that if we change licence of WeIO we can still potentially integrate your code without entering a complicated licence mixing (actually GPL is viral and demands all code linked to it to be GPL licenced).

BR,
Drasko

**Comment by cTn-dev** [comment]
Hi Drasko, i am not really planning to change the license, since i am not
really working on the sensor drivers anymore (i don't even own a python
capable hardware with I2C bus anymore).
That being said, you can feel free to integrate any of the libraries if you
choose to do so even when you later on decide to change the license of the
main project, its completely fine.

My drivers might still work with current version of python, but i would
recommend looking for some more evolved libraries because i am simply
unable to help you with the maintenance since i am no longer associated
with them.

Wish you a nice day

Stefan

**Comment by drasko** [comment]
Hi Stefan,
I am not licence specialist, but I don't think that we can just take your code and re-licence it under for example MIT, as we are not owners or authors. I think that only you can do this.

I think that it should be easy - just change LICENSE file an re-publish it under MIT or BSD.

Otherwise we will have to sign CLA, or what not that you transfer us right to close your code potentially.

We have to do a lot of work on writing practically same code that you have written. If you could publish it under more permissive licence we would be capable to contribute to your repo (there is more than 10 active contributors of WeIO project) and maintain it as a submodule to our project.

BR,
Drasko

**Comment by cTn-dev** [comment]
i switched the license to MIT, should be fine now

**Comment by drasko** [comment]
Great!!!

Many thanks Stefan. We will keep you informed about the progress.

We would also be honored if you get some interest in WeIO project - it should be similar to what you have been doing earlier and it seams that you have great skills. You will be most welcome to join our dev if you ever find creative itch for the stuff like this :).

Thanks again and best regards,
Drasko
